# Use root/example as user/password credentials
version: '3.1'

networks:
  mynetwork:

services:

  mysql:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: consultingDB
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_HOST: '%'
    labels:
      org.springframework.boot.service-connection: mysql
      org.springframework.boot.readiness-check.tcp.disable: false
    networks:
      - mynetwork

  consulting-api:
    build: 
      context: ./
      dockerfile: ./api/Dockerfile
    image: consulting-api
    ports:
      - 8080:8080
    networks:
      - mynetwork
    depends_on:
      - mysql
